---

development: 
  ARXIV_USER_AGENT: "Sangria/1.0 (mailto:you@example.com)"
  DB_FILENAME: db/local/dev.db
  SESSION_SECRET: rake new_session_secret to retrieve session secret
  API_HOST: http://localhost:[PORT NUMBER]

test: 
  ARXIV_USER_AGENT: "Sangria/1.0 (mailto:you@example.com)"
  DB_FILENAME: db/local/test.db
  SESSION_SECRET: rake new_session_secret to retrieve session secret
  API_HOST: http://localhost:[PORT NUMBER]


production: 
  ARXIV_USER_AGENT: "Sangria/1.0 (mailto:you@example.com)"